- name: Setup prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

#- name: Install utils
#  ansible.builtin.dnf:
#    name: yum-utils
#    state: installed

- name: Download hashicorp repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Copy vault config file to /etc/
  ansible.builtin.template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: Daemon reload and start the service
  ansible.builtin.systemd:
    name: vault
    daemon_reload: yes
    state: restarted
    enabled: yes
